### ISSUE TITLE
ToXaml doesn't work for me

### ISSUE THREAD

**Issue by ghost** [Kryptos-FR/markdig.wpf#1]
Following the same code as given in the sample
```cs
    var markdown = File.ReadAllText("Documents/Markdig-readme.md");
    var xaml = Markdig.Xaml.Markdown.ToXaml(markdown);
    FlowDocumentScrollViewer Viewer = new FlowDocumentScrollViewer();
    using (var stream = new MemoryStream(Encoding.UTF8.GetBytes(xaml)))
    {
        var reader = new XamlXmlReader(stream, new MyXamlSchemaContext());
        var document = System.Windows.Markup.XamlReader.Load(reader) as FlowDocument;
        if(document != null)
        {
            Viewer.Document = document;
        }
    }
```
I get an exception on `System.Windows.Markup.XamlReader.Load(reader) as FlowDocument;`
Here's the exception's message.
Provide value on 'Systems.Windows.StaticResourceExtension' threw an exception. Line number '1' and line position '178'.
EDIT:
Here's what the innerexception's message says "Cannot find resource named 'TargetType=Markdig.Wpf.Styles ID=DocumentStyleKey'. Resource names are case sensitive.".

**Comment by Kryptos-FR** [comment]
You need to provide styles for headings,etc. as specified by the resource keys defined in [`Markdig.Wpf.Styles`](https://github.com/Kryptos-FR/markdig-wpf/blob/master/src/Markdig.Wpf.Shared/Styles.cs). An example of such styles is given in the [generic.xaml](https://github.com/Kryptos-FR/markdig-wpf/blob/master/src/Markdig.Wpf.Shared/Themes/generic.xaml) resources file.

**Comment by ghost** [comment]
Thanks for replying! So should adding that project to my solution then referencing it be enough for it to locate the resources file? EDIT: Sorry, I'm not too good with wpf when it comes to styling/themes. I always just go with defaults when I can. This is the last leg of a messenger app I'm building though, so naturally I've got to have markdown support :P.

**Comment by Kryptos-FR** [comment]
You can reference the `Markdig.Wpf.Shared` project or just copy the files. Since `Markdig.Wpf.Shared` (as its name implies) is a "shared" project it is actually the same: files will just get included in your project.

You may want to modify the styles (in generic.xaml) though, I just set some arbitrary values to prove the concept. But I did not try to match a specific style.

**Comment by ghost** [comment]
Ah so then I guess my specific problem is that I'm using xamarin studio and it doesn't really like wpf not to mention wpf ResourceDictionaries. Is there anyway to parse the resourcedictionary from a file at runtime?

**Comment by Kryptos-FR** [comment]
Well to be fair I have no experience with non-WPF XAML. I thought that resource dictionaries and styles would be supported though as it is not really WPF-dependent.

Also Xamarin.Forms (did not get if you were using it or not) doesn't seem to support [FlowDocument](https://msdn.microsoft.com/en-us/library/system.windows.documents.flowdocument.aspx) which is required for rich-text content in this solution. You might be better off using [Markdig](https://github.com/lunet-io/markdig) directly and parse the HTML in a browser page (e.g. [WebView](https://developer.xamarin.com/api/type/Xamarin.Forms.WebView)) as in this example: [MarkdownViewer](https://developer.xamarin.com/samples/mac/MarkdownViewer).

**Comment by ghost** [comment]
Nah, I'm using wpf. Just everything in code-behind. And yes, it is as horrific as it sounds. But idk, it still can't find the resource.I tried not only referencing the shared project, but also directly putting it in my main project. Maybe I'll just create an ms account for use with vs2015. Thanks again!

**Comment by Kryptos-FR** [comment]
> Nah, I'm using wpf. Just everything in code-behind.

:scream:

Supposedly the whole resource file can be made in code-behind only. I never did it and it is probably very verbose but doable. Good luck! :sweat_smile:

**Comment by ghost** [comment]
Ha, thanks. I'm going to need wishes of good luck I think. And yes, 100% code-behind-ified wpf is awful and I will probably never do it again :wink:. And it didn't occur to me to try to make the resource file in code-behind too. I'll look into it, thanks!
