### ISSUE TITLE
Question: Is there a way to force a line break?

### ISSUE THREAD

**Issue by seb-giroux** [Kryptos-FR/markdig.wpf#14]
I have a bullet list followed by text, and whatever the nb. of enter I have in my .md file, it is not taken into account.

**Comment by jackgriffiths** [comment]
You can use backslashes to add extra line breaks:

```
* One
* Two
* Three

\
\
\
Test
```

**Comment by Kryptos-FR** [comment]
Hi @dheif.

Thanks for using the library.

Your issue has to do with commonmark specification itself: https://spec.commonmark.org/0.28/#hard-line-breaks.

Markdig.Wpf bases its rendering from the syntax parsed under the hood by the Markdig library.
Markdig also offers an extension to treat all **soft lines as hard lines** that you could consider enabling.

I'll close the issue for the time being but if you encounter another problem either by using @JackGriffiths suggestion or the Markdig extension, feel free to add a comment and I will investigate.
