### ISSUE TITLE
Design question: Why did you split the rendering in two seperated code trees?

### ISSUE THREAD

**Issue by neolithos** [Kryptos-FR/markdig.wpf#16]
**Why I ask**
- I need both, Text and Wpf output in the same quality and I am lazy enough to do not take care of two code bases.
- I have experience with the XamlParser of the .net framework, so I did a quick and dirty test with your library to show the way:
https://github.com/neolithos/markdig.wpf/commit/d1d5630cf5389c6af25c25c9d025dd9caf0a3ce1

**What are the changes**
The XamlRenderer emits xaml nodes, now. No text anymore.
I replaced the two methods ToXaml and ToFlowDocument to use only this output. WpfRenderer is not used anymore.

**Advantages**
- Only one codebase for the xaml code.

**Disadvantags**
- It might consume more time and resources.

**What is to do**
- A clean rewrite of the WpfRenderer with the XamlRenderer as backend in a higher code quality.
- Add a simple enough framework to emit xaml nodes, I am not happy with my current Q&D solution.

I can do this in your/this project, and I also will help you to maintain the library. Will you accept a pull request, when I am done? Or should I start a new project for this task?

**Comment by neolithos** [comment]
The wpf object emitter got a rewrite:
https://github.com/neolithos/markdig.wpf/commit/576e121bcdbb1994df48064a1ab3477fd3dfbf3d

**Comment by neolithos** [comment]
When can I expect a answer? Or do need anymore information?

**Comment by Kryptos-FR** [comment]
Hi @neolithos 

I just moved out recently and I don't have Internet in my new place yet. I'm also very busy at work so I can't spent time on that for the moment.

Once I get settled I will investigate your question in depth and give you a complete answer.

Thanks.

**Comment by neolithos** [comment]
Thanks, I startet this early enough to give that question time.

I have also a nice idea to support templating of the documents, but with this I will wait until you felt a decision.

Good look with your new home.

**Comment by neolithos** [comment]
Merged your changes to neolithos@f464e11ef2d8fa973ddbe121ea65b8e98351f412

And I had to edit these original pull requests:
#17: Is removed, because in my implementation all methods to write a extension are public.
#15: A q&d replacment is in the commit (neolithos@5f7a4f16d9af49d948937a0bf28b696b91418b66), needs tests and some performance tweaks

**Comment by neolithos** [comment]
Any progress on this?

**Comment by Kryptos-FR** [comment]
I had some thoughts about it and I don't think it makes sense to do XAML only and to get rid of the WPF renderer. In  most cases, users of the library do want to integrate it directly in to their application.

When you think of it, keeping a Xaml renderer doesn't make sense because in the final application you would be basically doing:
```
markdown -> parsing -> "rendering" into XAML -> parsing -> generating WPF objects
```
Whereas:
```
markdown -> parsing -> generating WPF objects
```

There is one more parsing happening in your solution. It is a waste of resources both CPU and memory.
And in the much less likely use of the library to generate `.xaml` file, you can dump it from any WPF objects.

In other word, I'm not going into the direction you suggested and if anything I might actually remove the XAML renderer. For that reason, I am closing it at "won't fix".

**Comment by neolithos** [comment]
That is not how my solution work. I got both with only one rendering implementation.

Generate Xaml:
```
markdown -> parsing -> rendering | write xml
```
Generate wpf-objects:
```
markdown -> parsing -> rendering | generate objects
```
To make it clear `write xml`and `generate objects` are implemented by the .net framework and are not part of the solution anymore (That is by the way the big pro).
`parsing` is done by markdig.
And only `rendering` is implemented by markdig.wpf. And has as task to generate a token stream for the .net framework xaml output writer. Less memory usage, less garbage collector.

Btw. I have no new parsing in my solution?

Is this your last word?
