### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by mgnslndh** [Kryptos-FR/markdig.wpf#2]
Hi,

I like what you are building. Are you planning on releasing it on Nuget?

**Comment by Kryptos-FR** [comment]
Hello.

I did not have much time recently to work on this project. A Nuget package is planned once the library reaches a stable state.

**Comment by Kryptos-FR** [comment]
cc @grokys Sorry to bother you but you seem to have some knowledge regarding creating and maintaining NuGet packages.

Ideally I would like `Markdig.Wpf` to support .Net Standard (as low as possible, considering `Markdig` itself supports .Net Standard 1.1). Should I make this change before attempting to publish on NuGet?
I also noticed in one of your branches you were removed C# 7 features. Is there a reason for that or was it more a matter of preference from your side?

**Comment by Kryptos-FR** [comment]
Forget it. I forgot that we merged the two projects (Xaml and Wpf) so of course .Net Standard is out of the picture.
Guess I can just publish as-is on NuGet then.

**Comment by grokys** [comment]
Ah - too late :)

If you could let me know when you publish the NuGet packages that would be great! I can hopefully remove the submodule.

**Comment by Kryptos-FR** [comment]
@mgnslndh @grokys NuGet package available: https://www.nuget.org/packages/Markdig.Wpf
Tell me if it works fine for you (first time I ever publish a package so I might have made a mistake).

**Comment by grokys** [comment]
@Kryptos-FR sorry I meant to comment on this earlier but then got distracted. Yep, the NuGet package works great, thanks for your work!
