### ISSUE TITLE
The type initializer for 'Markdig.Wpf.MarkdownViewer' threw an exception

### ISSUE THREAD

**Issue by FoggyFinder** [Kryptos-FR/markdig.wpf#20]
The code below doesn't compile with new version of markdig (0.15.5) 

```fsharp
open FsXaml

type TestWindowBase = XAML<"TestWindow.xaml">

type TestWindow(md) as self =
     inherit TestWindowBase ()

     do self.mdviewer.Markdown <- md

let sampleMD = """
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
"""

let window = sampleMD |> TestWindow 

[<EntryPoint>]
[<System.STAThread>]
let main argv =
    System.Windows.Application().Run window
```

where `TestWindow.xaml` is:

```xaml
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:markdig="clr-namespace:Markdig.Wpf;assembly=Markdig.Wpf">
    <Grid>
        <markdig:MarkdownViewer Name="mdviewer" />
    </Grid>
</Window>
```

It works fine with 0.15.4 although.

**Comment by Kryptos-FR** [comment]
If the problem is with markdig, you should open an issue to [markdig](https://github.com/lunet-io/markdig) repository, not here. I am not making that library and have no control over its development.

The latest version of markdig.wpf is built against markdig 0.15.4. So I recommend using that.

That said, I try with 0.15.5 and did not encounter any issue.

**Comment by FoggyFinder** [comment]
> If the problem is with markdig, you should open an issue to markdig repository, not here. I am not making that library and have no control over its development.

I surely can open issue there too but I think it is something with your library cause exception comes from 
`Markdig.Wpf.MarkdownViewer`.

> The latest version of markdig.wpf is built against markdig 0.15.4. So I recommend using that.

Yep, I pinned version to 0.15.4 for now in my dependency file to avoid exception.

**Comment by Kryptos-FR** [comment]
I had a second thought and your issue might be related to **binding redirects**, since you are attempting to use a version of `markdig` that `markdig.wpf` is not built against.

Have a look at the doc: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions

On a side-note: when you report an issue you need to provide a [minimum, complete and verifiable example](https://stackoverflow.com/help/mcve). Don't expect people to do the debugging for you and figure out where the issue is (hint: we don't have time). Since you had an exception, the minimum would have been to at least paste the exception message (+ stacktrace).

**Comment by FoggyFinder** [comment]
> I had a second thought and your issue might be related to binding redirects, since you are attempting to use a version of markdig that markdig.wpf is not built against.

Thank you. I don't think so although.

> On a side-note: when you report an issue you need to provide a minimum, complete and verifiable example. 

I did. It was MCVE there. Only 29 lines of code. Well, yep I can minimize it to something like:

```fsharp
type TestWindowBase = FsXaml.XAML<"TestWindow.xaml">
type TestWindow(md) as self =
     inherit TestWindowBase ()
     do self.mdviewer.Markdown <- md
[<EntryPoint>][<System.STAThread>] 
let main _ = 
    "#Sample" |> TestWindow |> System.Windows.Application().Run
```

I attach project: [MarkdigMCVE.zip](https://github.com/Kryptos-FR/markdig.wpf/files/2684979/MarkdigMCVE.zip)

> Since you had an exception, the minimum would have been to at least paste the exception message (+ stacktrace).

It is compile time exception. I provided additional information if I would know it. There is also error from XAML designer:

> Method not found: 'Markdig.MarkdownPipelineBuilder Markdig.MarkdownExtensions.UseAutoLinks(Markdig.MarkdownPipelineBuilder)'

> Don't expect people to do the debugging for you and figure out where the issue is (hint: we don't have time).

I don't expect, honestly :-) I have seen the exception and decided to report. Nothing else. That's not really important to me cause version 0.15.4 works perfectly.

**Comment by Kryptos-FR** [comment]
@FoggyFinder I just read the discussion on the markdig issue.

Honestly I made a wrong assumption that binary compatibility would not break between minor versions of markdig. I will not make such assumption anymore ;)

I'm still surprised that you got the error at compile time. I would have expect it to break only at runtime. Maybe the fsharp compiler works differently.

Anyway, thanks for pointing out the issue. And I did not even know that markdig and WPF could be used in fsharp projects. I guess I'll have to learn that language now.

**Comment by FoggyFinder** [comment]
> I'm still surprised that you got the error at compile time. I would have expect it to break only at runtime. Maybe the fsharp compiler works differently.

It is a [type provider](https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/type-providers/). Very convenience sometimes. I used [FsXaml](https://fsprojects.github.io/FsXaml/) here because I used it in all my WPF projects.

> And I did not even know that markdig and WPF could be used in fsharp projects. I guess I'll have to learn that language now.

Yep, F# is awesome

**Comment by Kryptos-FR** [comment]
I was able to reproduce at runtime with a csharp application. The cuplrit was the `UseAutoLinks()` extension method in markdig that now has a second optional parameter. From now on and until markdig goes beyond version `0.*` I will package markdig.wpf to match the exact version it is built against.
