### ISSUE TITLE
Could you update to Markdig 0.15.7?

### ISSUE THREAD

**Issue by Tokter** [Kryptos-FR/markdig.wpf#22]
Thanks!

**Comment by Kryptos-FR** [comment]
So that's it? No explanation to why I should do that?

Are you going to pay me? What if I say no? :wink:

**Comment by Tokter** [comment]
Sorry, didn't mean to offend you:

_So that's it? No explanation to why I should do that?_
You set the nuget dependency to Markdig (= 0.15.5). That means I can't update Markdig itself to the latest version. 

_Are you going to pay me? What if I say no? 😉_
I could create a pull request for it if you want, or fork your nice work.

**Comment by Kryptos-FR** [comment]
@Tokter I was being a bit sarcastic (and a bit tired from work), sorry 😄 

The reason the version is set to exactly match Markdig is because of issue #20.
I have updated the version to markdig 0.16.0 and a package is being published (make take a few hours before being visible).
