### ISSUE TITLE
Update to allow rendering into an exciting FlowDocument with content and styling

### ISSUE THREAD

**Issue by dornstein** [Kryptos-FR/markdig.wpf#23]
Hi there -- I'm looking for a component that I can use to render (commonmark) markdown into a flow document.  markdig.wpf looks awesome -- except the flow document I'll be rendering into already has content and styles and such.  I want to append the rendered markdown into the document without any assumptions about what might already be in the flow document or how it might be styled.  A quick skim of your code seems to show that you'll probably work OK if appending, but you do seem to make some assumptions about being able to set the style of the document overall which may collide with any styling already on the flow document.  Any thoughts about this scenario?

**Comment by Kryptos-FR** [comment]
The styling works by having a couple of StyleKey that you can override easily. There is a default theme but you can replace it with your own.

**Comment by Kryptos-FR** [comment]
@dornstein does it answer your question?
