### ISSUE TITLE
Nuget package doesn't apply to .Net 4.5 project

### ISSUE THREAD

**Issue by mengluwang121** [Kryptos-FR/markdig.wpf#25]
Hi,

Thanks for providing this awesome code to make Markdown in WPF much easier!
I am from VisualStudio setup team and we are considering using this package in a .Net 4.5 project for Markdown support. I do saw the change to retargeting the project to .net 4.0, but it seems the nuget package on market still only targeting .Net 452. I am wondering could you please take a look?
Really appreciate your help!

Best,
Menglu

**Comment by Kryptos-FR** [comment]
Hi @mengluwang121.

Thanks for your interest in my humble project. I indeed made the change but did not package a new version that supports net40. I'll make a new package to that end.

Any reason why you need it to target net45 but not net452?

**Comment by Kryptos-FR** [comment]
v0.2.8 released. Please wait a few minutes (hours?) before the package is indexed by nuget.

**Comment by mengluwang121** [comment]
Thank you so much for the quick response!!! : P

Targeting 4.5 was an architecture decision we made to support older os like win8 etc.
