### ISSUE TITLE
Port to .net core 3.0

### ISSUE THREAD

**Issue by hillin** [Kryptos-FR/markdig.wpf#26]
WPF is coming to .net core now. Is there any plan to port markdig.wpf to .net core 3.0?

**Comment by Kryptos-FR** [comment]
Good question.

I will wait for the official release before doing any work on that. I don't expect a lot of issues (if any) as there are very few dependencies and the use of `FlowDocument` and related types, is pretty standard.

**Comment by Kryptos-FR** [comment]
.NET core is added as a target thanks to #35
