### ISSUE TITLE
How to change default fontfamily?

### ISSUE THREAD

**Issue by chenxuuu** [Kryptos-FR/markdig.wpf#30]
default font is not right, how to change it?

**Comment by Kryptos-FR** [comment]
You can override any style you want.

See https://github.com/Kryptos-FR/markdig.wpf/blob/develop/src/Markdig.Wpf/Themes/generic.xaml

----
Closed as duplicate of #23 and #24.

**Comment by chenxuuu** [comment]
I see
thanks!
