### ISSUE TITLE
Make classes customizable

### ISSUE THREAD

**Issue by FCUnlimited** [Kryptos-FR/markdig.wpf#32]
Hi,

thanks for providing the code. I love his clear and easy structure!

I made some changes on a local branch, which make it possible to customize the WPF Renderer.
So I declared some functions as protected and added also some optional parameter.

I also made the WPF Image clickable. So if you click an image the associated command will be executed. In my case to zoom into it.

I would like to share it with you

Best
FC

**Comment by Kryptos-FR** [comment]
Looks interesting. Feel free to open a draft pull-request so we can discuss the code.

**Comment by FCUnlimited** [comment]
Done. My first one :)
