### ISSUE TITLE
[Bug] (MarkdownViewer Control) Markdown content cannot have 0 as starting index for numbered lists

### ISSUE THREAD

**Issue by chaojian-zhang** [Kryptos-FR/markdig.wpf#34]
The `Markdown` property of MarkdownViewer control seem not able to have 0 in a numbered list. An **ArgumentException** will be thrown saying `0 is not a valid StartIndex`. 

I am not sure whether this is related to `MarkdownPipelineBuilder` or I need to enable some `UseSupportedExtensions()`?

![Exception](https://user-images.githubusercontent.com/7077098/64467047-221d2600-d0e3-11e9-9e3b-a4710d606957.png)

VS Setup: [MarkdigWPFNumberList.zip](https://github.com/Kryptos-FR/markdig.wpf/files/3586068/MarkdigWPFNumberList.zip)

**Comment by Kryptos-FR** [comment]
As far as the commonmark specification goes, ordered list must start with *1*.

Source: https://spec.commonmark.org/0.29/#ordered-list-marker

**Comment by chaojian-zhang** [comment]
I checked the [spec](https://spec.commonmark.org/0.29/#ordered-list-marker) and think the line **"An ordered list marker is a sequence of 1–9 arabic digits (0-9), followed by either a . character or a ) character.**" clearly allows it.

Also see this [discussion](https://github.com/markdown-it/markdown-it/issues/129). 

Thanks.

**Comment by Kryptos-FR** [comment]
I guess you misunderstand the spec. It clearly states that it must start with *1*. That's what **sequence 1-9** means. And later in the paragraph it is even more explicit: **the start number must be 1**.

In any case, *markdig.wpf* relies on what the *markdig* library parses. So if you think it is a bug, you should open an issue there.

But as can be seen in the [babelmark benchmark](https://babelmark.github.io/?text=This+is+an+ordered+list%3A%0A0.+Item+0%0A1.+Item+1%0A2.+Item+2), all commonmark-complying implementations don't support 0 as a starting index.

Final note, this exception happens in WPF (PresentationFramework) implementation of List (in namespace System.Windows.Documents), so there is nothing I can do about it unfortunately:
- https://docs.microsoft.com/en-us/dotnet/api/system.windows.documents.list.startindex?view=netframework-4.8#System_Windows_Documents_List_StartIndex)
- https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Documents/List.cs
