### ISSUE TITLE
WPFRenderer customization to enable (some css) styling in MarkdownViewer

### ISSUE THREAD

**Issue by dgbeer20** [Kryptos-FR/markdig.wpf#39]
Hi, 

How can I start with a custom WPF rendering of simple inline HTML code like <span style="color:blue">blue</span> within a markdown document? The aim is to have some simple styling (color, background, ...) that can be seen in the MarkdownViewer.

Thanks, 
Daniel

**Comment by Kryptos-FR** [comment]
I don't plan to support such feature. The goal of this project is not to transform HTML into WPF, there are other alternatives. HTML is not part of common-mark and this project only support common-mark.

You can define styling for all parts of the rich text that is the translation of the markdown document.

See #23, #24, #30 or #31
