### ISSUE TITLE
Discussion: should we keep support for net40 and net45?

### ISSUE THREAD

**Issue by Kryptos-FR** [Kryptos-FR/markdig.wpf#41]
Recently, [Markdig](https://github.com/lunet-io/markdig) which this project relies on, has dropped for `net35`and `net40` (see https://github.com/lunet-io/markdig/pull/416).

It means that we can't upgrade the version we use anymore. So I am opening a discussion to decide what we should do from now on.

cc @mengluwang121 you were the one to request support for `net45` (and not `net452`) in #25. Is it still a requirement?

**Comment by Kryptos-FR** [comment]
Update: @xoofx has agreed to keep support for `net452` for now (to be retired at a later date). See https://github.com/lunet-io/markdig/pull/466.

According to VS2017 or VS2019 requirements page, `net452` is expected to be on the machine prior to installation and not `net45`. @mengluwang121 is it fine if I also drop support for versions lower than `net452`?

**Comment by mengluwang121** [comment]
Hi,
Thanks for reaching out. Our project is still targeting .net4.5 (we are the installer so the requirement is slightly different than the IDE) I'll talk  to my team and get back to you to see what our plan it. Thanks you so very much!

**Comment by Kryptos-FR** [comment]
Given that `net40` has been out of support for more than 4 years (see [Support Ending for the .NET Framework 4, 4.5 and 4.5.1](https://devblogs.microsoft.com/dotnet/support-ending-for-the-net-framework-4-4-5-and-4-5-1/), there is little sense keeping it. Therefore the final decision is to drop it for Markdig.wpf.

However, `net452` is supported until January 2023 (as part of Windows 8.1 lifecycle), so we will keep it until either this expiration or if Markdig drops support for it sooner ; there were kind enough to put back the support for now, but it might change again in the future.

**Comment by mengluwang121** [comment]
Hi,

Sorry for late response. After discussion, our repo cannot target to .net4.5.2 yet... I am wondering could we added back the support for .net4.5? Since we want to take advantage of the newly added paragraph feature we want to update our version of your package. Thank you so very much!!!

Best,
Menglu

**Comment by Kryptos-FR** [comment]
@mengluwang121 I'm sorry but I can't add back that support. It is an obsolete version that is not supported and won't receive any security updates. There is no reason to keep it around.

In a previous issue, you said you were working on a Visual Studio Setup project. Can you tell me more about it? As far as I can see, from the [system requirements page of the Visual Studio](https://docs.microsoft.com/en-us/visualstudio/releases/2019/system-requirements), .NET 4.5.2 is already a requirement. For what purpose do you still need `net40`? None of the currently supported versions of Windows ship such a low version of the runtime.

**Comment by mengluwang121** [comment]
We are on Visual Studio Installer team (new installer will be released soon). The reason we need to keep our framework on 4.5 is win 7 machines come with 4.5, even if it is out of support now, as an Installer we have to support it. "System requirements page of the Visual Studio, .NET 4.5.2 is already a requirement" is a public announcement but in underlying code, our project still have to support 4.5. Sorry for the confusion. I are looking move our framework to 4.7 later, but it cannot be done at current moment :(

**Comment by Kryptos-FR** [comment]
`Markdig` doesn't support `net45` anymore, so there really is nothing I can do on my side. You will have to use an earlier version.

I am still quite surprised to read that you have to support Win7 given that the OS is out of support, and even for people still using it, they should now have had `net452` runtime installed as an automated Windows Update 4 years ago, when both `net45`and `net451` went out of support.

Since we are talking about a development tool (Visual Studio), I can't think of any developer in the whole world that would still work on a machine that can only produce applications and libraries on obsolete and unsupported platform. Surely, a developer would always have a more recent (if not the most recent) set of tools to do their work. Your scenario sounds really unrealistic to me.
