### ISSUE TITLE
Emoji style

### ISSUE THREAD

**Issue by EgilSandfeld** [Kryptos-FR/markdig.wpf#52]
Is there a way to style just the emojis in a markdown, like making them yellow or [their original colors](https://github.com/xoofx/markdig/blob/master/src/Markdig/Extensions/Emoji/EmojiMapping.cs)?

This is how it looks in my app:
![Emoji style missing](https://i.imgur.com/wCWvBPT.png)

**Comment by Kryptos-FR** [comment]
Unfortunately, this is outside the scope of this library.

The rendering is done by WPF and it has a long-standing issue about rendering emojis with colors as can be seen here: https://github.com/dotnet/wpf/issues/91

With that said, there is an attempt at fixing it in this other library: https://github.com/samhocevar/emoji.wpf. So this could be investigated.

**Comment by Kryptos-FR** [comment]
A little experiment with `Emoji.Wpf` shows that it is working. What you need to do is:
1. Add `Emoji.Wpf` package as reference
2. Modify the style for `FlowDocument` in your app as follows:
```xaml
<Window x:Class="Markdig.Wpf.SampleApp.MainWindow"
        ...
        xmlns:markdig="clr-namespace:Markdig.Wpf;assembly=Markdig.Wpf"
        xmlns:emoji="clr-namespace:Emoji.Wpf;assembly=Emoji.Wpf">
  <FrameworkElement.Resources>
    <Style TargetType="FlowDocument" x:Key="{x:Static markdig:Styles.DocumentStyleKey}">
      <Setter Property="emoji:Behaviors.EmojiRendering" Value="True" />
      <!-- following lines copied from the generic theme, feel free to change to fit your own theme -->
      <Setter Property="FontFamily" Value="Calibri" />
      <Setter Property="TextAlignment" Value="Left" />
    </Style>
  </FrameworkElement.Resources>
  <markdig:MarkdownViewer x:Name="Viewer"/>
</Window>
```

**Comment by EgilSandfeld** [comment]
Thank you so much, @Kryptos-FR 🚀💪
This was very easy to implement. Works wonders now

![](https://i.imgur.com/N4hFIhC.png)
