### ISSUE TITLE
Links not work at all

### ISSUE THREAD

**Issue by LexaGV** [Kryptos-FR/markdig.wpf#53]
I made MD hyperlink with `[]()` syntax and see that link is rendered properly in a `FlowDocument`. BUT... when I click link, nothing happens! Why? I expect link will open browser with given URL.

When I investigated this bug, people also had the same problem, but with normally created `FlowDocument`. They simply assign to link `RequestNavigate` handler and in a handler they call `Process.Start()`. I tried the same with your `FlowDocument`, but no luck - this handler never ever called. In WPF logs I saw no error, so code is OK. When I manually created `Hyperlink` and assigned `RequestNavigate`, code works. That means your WPF renderer creates "invalid" `Hyperlink` that it cannot even call own handler.

Solution: make please link behave as a link! Not a huge job, but annoying when link doesn't behave as it must.

**Comment by Kryptos-FR** [comment]
Links are working. You need to assign a command as shown in the samples.

**xaml**
```xaml
<CommandBindings>
  <CommandBinding Command="{x:Static markdig:Commands.Hyperlink}" Executed="OpenHyperlink" />
</CommandBindings>
```

**code-behind**
```csharp
private void OpenHyperlink(object sender, System.Windows.Input.ExecutedRoutedEventArgs e)
{
  Process.Start(e.Parameter.ToString());
}
```
