### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by 2366621450** [Kryptos-FR/markdig.wpf#59]
Hello
How to set text alignment in xaml files?
The width is always stretched by default. How to cancel the always stretch in the xaml file? I want to stretch the width based on the size of the content.
I tried using styles to solve the text alignment problem, but the width is always stretched by default, so the effect is not ideal.

**Comment by Kryptos-FR** [comment]
Hello, I think you should be able to achieve this with styling.

Also note that because of a lack of time, I'll archive this repo until further notice. When my situation improves I might unarchive it and resume work.
